<main>

<!--
    <section class="index-login">
        <div class="index-login-loguin">
            <h4>WRONG PASWORD!</h4>
            <P>Try it again!</P>
            <form action="/web/" method="POST">
                <br>
                <button type="submit" name="submit">GO!</button>
            </form>
        </div>
        </div>
    </section>
-->



    <div class="max-w-2xl mx-auto my-10">
        <div
            class="bg-white shadow-md border border-gray-200 rounded-lg max-w-sm p-4 sm:p-6 lg:p-8 dark:bg-gray-800 dark:border-gray-700">
            <form action="/web/" method="POST" class="space-y-6" action="/web/login" method="POST">
                <h3 class="text-xl font-medium text-red-500 dark:text-white ">WRONG PASWORD!</h3>
                <p class="text-sm font-medium text-gray-900 block mb-2 dark:text-gray-300">Try it again!</p>
                <div class="flex items-start"></div>
                <button type="submit" name="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 
                        text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Login to your
                    account</button>
        </div>
        </form>
    </div>

    </div>
    </section>