<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loguin</title>
</head>
<body>

<section class="index-login">
        <div class="index-login-signup">
            <h4>SING UP</h4>
            <P>Don't have an account yet? Sing up here!</P>
            <form action="/web/signup" method="POST">
                <input type="text" name="uid" placeholder="Username">
                <input type="password" name="pwd" placeholder="Password">
                <input type="password" name="pwdrepaeat" placeholder="Repeat Password">
                <input type="text" name="email" placeholder="E-mail">
                <br>
                <button type="submit" name="submit">SING UP</button>
            </form>
        </div>
    </div>
</section>
    
</body>
</html>