<!DOCTYPE html>

<html lang="es">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="author" content="Rodrigo Saiz, Susana Gil" />
	<title>TODO-List</title>
	<script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-gray-100">
	<div>

		<?php echo $this->content(); ?>
		</main>
		<footer class="p-4 bg-white rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800">
			<span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 - IT-ACADEMY Developers: <a
					href="https://github.com/rodrisaiz/" class="hover:underline" target="_blank">Rodri Saiz</a> & <a
					href="https://github.com/sgilcastro" class="hover:underline" target="_blank">Susana Gil</a>. All
				Rights Reserved.
			</span>

			<ul class="flex flex-wrap items-center mt-3 sm:mt-0">
				<li>
					<a href="/README.md" class="mr-4 text-sm text-gray-500 hover:underline md:mr-6 dark:text-gray-400">README</a>
				</li>
				<!-- <li>
					<a href="#" class="mr-4 text-sm text-gray-500 hover:underline md:mr-6 dark:text-gray-400">Privacy
						Policy</a>
				</li>
				<li>
					<a href="#"
						class="mr-4 text-sm text-gray-500 hover:underline md:mr-6 dark:text-gray-400">Licensing</a>
				</li>
				<li>
					<a href="#" class="text-sm text-gray-500 hover:underline dark:text-gray-400">Contact</a>
				</li> -->
			</ul>
		</footer>
	</div>
</body>

</html>